rimossi file non piu necessari non essendo piu un progetto sam, mofdificato nginx.conf su porta 5000, aggiornato buildspec e creato backup del Dockerfile per tenere traccia deglis tep condizionali

diff --git a/Dockerfile_bck b/Dockerfile_bck
--- a/Dockerfile_bck
+++ b/Dockerfile_bck
@@ -15,7 +15,10 @@ ARG EFS_MOUNT_PATH
 ENV EFS_MOUNT_PATH=$EFS_MOUNT_PATH
 
 ARG DEV=false
-RUN dnf install -y ca-certificates \
+RUN #if [ -z "$EFS_MOUNT_PATH" ]; then \
+    #  echo -e '\033[0;31mError: environment variable EFS_MOUNT_PATH not provided.\033[0m' && exit 4; \
+    #fi && \
+    dnf install -y ca-certificates \
                    fontconfig \
                    freetype \
                    glibc \
@@ -43,6 +46,13 @@ RUN dnf install -y ca-certificates \
     chown -R user:user /var/log/nginx && \
     chown -R user:user /var/lib/nginx && \
     chown -R user:user /run/nginx.pid
+#    if [ $DEV = "true" ]; then \
+#        pip install -r requirements.dev.txt && \
+#        mkdir -p "$EFS_MOUNT_PATH" && \
+#        chown -R user:user "$EFS_MOUNT_PATH"; \
+#    else \
+#        rm test_* *.json entrypoint.dev.sh .coveragerc .bandit requirements*; \
+#    fi
 
 USER user
 
